name: Example CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Any
        run: echo Hello

      - name: multi line job
        run: |
          echo this is
          echo multi line job
